package Week12OOPInheritanceInJava.Class12point9StaticVariablesInJava;
/*
Description: Create a class called Transaction that represents a financial transaction. The class should have several static variables, several instance variables, two static methods, and two instance methods.

Class: Transaction

Static Variables:

transactionCount (int): Represents the total count of transactions performed.

bankName (String): Represents the name of the bank.

Instance Variables:

transactionId (String): Represents the unique ID of the transaction. Should be generated by the class like "T1", "T2", "T3", and so on.

accountNumber (String): Represents the account number associated with the transaction.

amount (double): Represents the amount of money involved in the transaction.

isSuccessful (boolean): Indicates whether the transaction was successful or not.

Construtors:

two param constructor with accountNumber and amount.

Static Methods:

getBankName(): Returns the name of the bank.

setBankName(String name): Sets the name of the bank.

Instance Methods:

Transaction(String accountNumber, double amount): Initializes the transaction object with the provided account number and amount.
The transaction ID is generated automatically based on the current transaction count.

processTransaction(): Simulates the processing of the transaction. If the transaction ID is even, the isSuccessful variable is set to true.

displayTransactionDetails(): Displays the details of the transaction, including the transaction ID, account number, amount, and success status.

Additional Static Method:

calculatePercentage(double percentage, Transaction transaction): Calculates the percentage of the transaction
amount based on the given percentage value. If the transaction is successful, it returns the calculated percentage of the amount.
Otherwise, it returns 0.

getTransactionCount(): Returns the total number of transactions.

Example:

Transaction.setBankName("ABC Bank");

Transaction transaction1 = new Transaction("1234567890", 100.0);

transaction1.processTransaction();

transaction1.displayTransactionDetails();

System.out.println();

Transaction transaction2 = new Transaction("9876543210", 200.0);

transaction2.processTransaction();

transaction2.displayTransactionDetails();

System.out.println();

double percentage1 = Transaction.calculatePercentage(10, transaction1);

System.out.println("Transaction 1 Percentage: " + percentage1 + "%");

double percentage2 = Transaction.calculatePercentage(5, transaction2);

System.out.println("Transaction 2 Percentage: " + percentage2 + "%");

System.out.println("Total Transactions: " + Transaction.getTransactionCount());

System.out.println("Bank Name: " + Transaction.getBankName());

Output:

Transaction Details:

Transaction ID: T1

Account Number: 1234567890

Amount: $100.0

Successful: false

Transaction Details:

Transaction ID: T2

Account Number: 9876543210

Amount: $200.0

Successful: true

Transaction 1 Percentage: 0.0%

Transaction 2 Percentage: 4.0%

Total Transactions: 2

Bank Name: ABC Bank
 */
public class Transactionpt1 {
    public static void main(String[] args) {

    }
}
class Transaction {
    // Static Variables:
    private static int transactionCount; // Static variable to keep track of total transactions
    private static String bankName; // Static variable to store the name of the bank

    // Instance Variables:
    private String transactionId; // Unique ID for each transaction
    private String accountNumber; // Account number associated with the transaction
    private double amount; // Transaction amount
    private boolean isSuccessful; // Whether the transaction was successful or not

    // Constructors:
    public Transaction(String accountNumber, double amount) {
        this.accountNumber = accountNumber;
        this.amount = amount;
        this.transactionId = "T" + (++transactionCount); // Increment and assign a unique transaction ID
    }

    // Static Methods:
    public static String getBankName() {
        return bankName; // Retrieve the name of the bank
    }

    public static void setBankName(String name) {
        bankName = name; // Set the name of the bank
    }

    public static int getTransactionCount() {
        return transactionCount; // Retrieve the total transaction count
    }

    public static double calculatePercentage(double percentage, Transaction transaction) {
        if (transaction.isSuccessful) {
            return (percentage / 100.0) * transaction.amount; // Calculate the percentage of transaction amount
        } else {
            return 0; // If the transaction was not successful, return 0
        }
    }

    // Instance Methods:
    public void processTransaction() {
        isSuccessful = Integer.parseInt(transactionId.substring(1)) % 2 == 0; // Check if the transaction ID is even
    }

    public void displayTransactionDetails() {
        // Display a header for transaction details
        System.out.println("Transaction Details:");

        // Display the transaction ID
        System.out.println("Transaction ID: " + transactionId);

        // Display the account number associated with the transaction
        System.out.println("Account Number: " + accountNumber);

        // Display the amount of the transaction with a dollar sign
        System.out.println("Amount: $" + amount);

        // Display whether the transaction was successful or not
        System.out.println("Successful: " + isSuccessful);
    }

    public static void main(String[] args) {
        Transaction.setBankName("ABC Bank"); // Set the bank name

        Transaction transaction1 = new Transaction("1234567890", 100.0); // Create a new transaction
        transaction1.processTransaction(); // Process the transaction
        transaction1.displayTransactionDetails(); // Display transaction details

        Transaction transaction2 = new Transaction("9876543210", 200.0); // Create another transaction
        transaction2.processTransaction(); // Process the transaction
        transaction2.displayTransactionDetails(); // Display transaction details

        double percentage1 = Transaction.calculatePercentage(10, transaction1); // Calculate percentage for transaction 1
        System.out.println("Transaction 1 Percentage: " + percentage1 + "%");

        double percentage2 = Transaction.calculatePercentage(5, transaction2); // Calculate percentage for transaction 2
        System.out.println("Transaction 2 Percentage: " + percentage2 + "%");

        System.out.println("Total Transactions: " + Transaction.getTransactionCount()); // Display total transaction count
        System.out.println("Bank Name: " + Transaction.getBankName()); // Display bank name
    }
}
